%\VignetteIndexEntry{Analyzing RNA-seq data for differential exon usage with the "DEXSeq" package}
%\VignettePackage{DEXSeq}

% To compile this document
% library('weaver'); rm(list=ls()); unlink("DEXSeqReport", recursive=TRUE); Sweave('DEXSeq.Rnw', driver=weaver()); system('pdflatex DEXSeq')

\documentclass{article}

\usepackage{Sweave}
\usepackage[a4paper]{geometry}
\usepackage{hyperref,graphicx}
\usepackage{cite}
\usepackage{color}

\SweaveOpts{keep.source=FALSE,eps=FALSE,include=FALSE,width=4,height=4.5} 
\newcommand{\Robject}[1]{\texttt{#1}}
\newcommand{\Rpackage}[1]{\textit{#1}}
\newcommand{\Rclass}[1]{\textit{#1}}
\newcommand{\Rfunction}[1]{{\small\texttt{#1}}}
\newcommand{\fixme}[1]{{\textbf{Fixme:} \textit{\textcolor{blue}{#1}}}}

\renewcommand{\floatpagefraction}{0.7}	

\title{\textsf{\textbf{Analyzing RNA-seq data for differential exon usage with the \Rpackage{DEXSeq} package}}}
\author{Alejandro Reyes, Simon Anders, Wolfgang Huber}

\begin{document}
\maketitle
\tableofcontents

\begin{abstract}
  RNA-seq is a powerful tool for transcriptome analysis. It enables
  the discovery of novel transcript splice sites and isoforms, and
  there is interest in the quantitative comparison of exon usage
  between different conditions.  For the analysis of differential
  expression between conditions, appropriate modeling of the
  experimental and biological variability is important, and such
  capabilities are offered, for instance, by the packages
  \Rpackage{edgeR}~\cite{edgeR} and
  \Rpackage{DESeq}~\cite{Anders:2010:GB}. However, there is currently no
  software that specifically addresses exon level expression and
  differential exon usage.  In this package, we provide a method to
  systematically detect differential exon usage using RNA-seq.  We use
  as input the number of reads mapping to each of the exons of a
  genome. The method is demonstrated on the data from the package
  \Rpackage{pasilla}. 
\end{abstract}

%-----------------------------------------------------------
\section{The Pasilla dataset}
%-----------------------------------------------------------
We will use the \Robject{pasillaExons} dataset from the \Rpackage{pasilla} package. 
\Robject{pasillaExons} is an object of class \Rclass{ExonCountSet}.
Brooks et al.~\cite{Brooks2010} investigated the effect of siRNA knock-down of Pasilla, whose protein
is known to bind to mRNA in the spliceosome, and which is thought to be involved 
in the regulation of splicing, on the transcriptome of fly S2-DRSC cells.  
Pasilla is the Drosophila melanogaster ortholog of mammalian NOVA1 and NOVA2.
The dataset, which is provided by NCBI Gene Expression Omnibus (GEO) under the accession number
GSE18508\footnote{\url{http://www.ncbi.nlm.nih.gov/projects/geo/query/acc.cgi?acc=GSE18508}}, 
contains 3 biological replicates of the knockdown as well as 4 biological replicates for the untreated control. 

In the \Rpackage{pasilla} package, we provide data from a subset of
genes.  A subset was chosen in order to speed up the computations
shown in this vignette. We start by loading the \Rpackage{DEXSeq}
package and the example data.

<<options,results=hide,echo=FALSE>>=
options(digits=3)
@  
<<start,results=hide>>=
library("DEXSeq")
<<datapasilla>>=
data("pasillaExons", package="pasilla")
@ 
The \Rfunction{pData} accessor function shows the available sample annotations.
<<pData>>=
pData(pasillaExons)
@ 
We also print the first \Sexpr{formals(utils:::head.data.frame)$n} lines of selected
columns of the feature data annotation:
<<fData>>=
head(fData(pasillaExons)[,c(1,2,7:10)])
@   
<<tabtab1,echo=FALSE>>=
tg = table(geneIDs(pasillaExons)) 
tt = table(tg)
stopifnot(tt["36"]==1, tt["16"]==3)
@ 
There are \Sexpr{sum(tg>0)} genes in the dataset, of these, there is one with 36 exons, and for instance,
three with 16 exons:
<<tabtab2>>=
table(table(geneIDs(pasillaExons))) 
@ 
In Section~\ref{sec:creating}, we explain how to create analogous data objects from your own data.

%--------------------------------------------------
\section{Normalisation and dispersion estimation}\label{sec:norm}
%--------------------------------------------------
Different samples might be sequenced with different depths. In order to adjust for such coverage biases, 
we introduce size factor parameters.  \Rpackage{DEXSeq} uses the same method
as \Rpackage{DESeq}, which is provided in the function \Rfunction{estimateSizeFactors}. 
<<sizeFactors1,cache=TRUE>>=
pasillaExons <- estimateSizeFactors(pasillaExons)
<<sizeFactors2>>=
sizeFactors(pasillaExons)
@

To test for differential expression, we need to estimate the data's variance, in order
to distinguish between normal technical and biological variation (noise) and real effects
on gene expression between the different conditions.  
The information on the size of the noise is drawn from the biological replicates in the dataset.
However, as typical for RNA-seq experiments, the number of replicates is too small to estimate
vatiance or dispesion parameters individually gene by gene. Instead, variance information is shared
across genes, in an intensity dependent manner. Computationally, this is done through Cox-Reid 
likelihood estimation (our method follows that of the package \Rpackage{edgeR}~\cite{edgeR}), and 
by fitting a mean dependent regression over the dispersions. These steps are implemented in the 
function \Rfunction{estimateDispersions}.
%
<<estDisp1,cache=TRUE,results=hide>>=
pasillaExons <- estimateDispersions(pasillaExons)
<<estDisp2>>=
head(featureData(pasillaExons)$dispersion)
head(featureData(pasillaExons)$dispersion_CR_est)
@
%
In Section~\ref{sec:glm}, we will see how to incorporate further experimental or technical variables
into the dispersion estimation.

\fixme{Why are the two dispersion estimates so different, and why do we need to show them both? 
See Figure~\ref{figCR} and below.}

<<figCR,fig=TRUE>>=
plot(fData(pasillaExons)[,c("dispersion","dispersion_CR_est")], xlim=c(0,50))
abline(a=0,b=1,col="orange")
@ 
<<weird>>=
weird = function(x) table( (x>50) | (!is.finite(x)))
weird(fData(pasillaExons)$dispersion)
weird(fData(pasillaExons)$dispersion_CR_est)
@ 
\begin{figure}
\centering
\includegraphics[width=0.5\textwidth]{DEXSeq-figCR}
\caption{Comparison of two different dispersion estimates.}
\label{figCR}
\end{figure}
     

%--------------------------------------------------
\section{Testing for differential exon usage}
%--------------------------------------------------
Having the dispersion estimates and the size factors, we can now test for differential exon usage. 
For each gene, we fit a generalized linear model with the formula
\[
\mbox{\texttt{sample + exon + condition * I(exon == exonID)}}
\]
and compare it to the smaller model (the null model) 
\[
\mbox{\texttt{sample + exon + condition}.}
\]
We compare the deviances of both fits using a $\chi^2$-distribution. 
To create a data frame that encodes the model for a gene, with
columns \texttt{sample}, \texttt{exon}, \texttt{condition}, \texttt{sizeFactors} and 
\texttt{count}, the function \Rfunction{modelFrameForGene} is used.
<<mffg1>>=
head( modelFrameForGene( pasillaExons, "FBgn0010909" ) )
@ 
The actual test (which already includes a call to \Rfunction{modelFrameForGene}) is
performed by the function \Rfunction{testGeneForDEU}:  
<<mffg2>>=
testGeneForDEU( pasillaExons, "FBgn0010909" )
@
<<mffg3,echo=FALSE,results=hide>>=
tgdeu = testGeneForDEU( pasillaExons, "FBgn0010909" )
specialExon = "E010"
stopifnot(tgdeu[specialExon,"pvalue"]<1e-7)
@ 
We see that there is one exon, \texttt{\Sexpr{specialExon}}, with a very small $p$ value, while for all other exons,
the $p$ values are unremarkable.

A convenient interface which calls \Rfunction{testGeneForDEU} for all genes
and fills the \Robject{pvalue} and \Robject{padjust} columns of the \Robject{featureData} slots 
of the \Rclass{ExonCountSet} object with the results is provided by the
function \Rfunction{testForDEU}.  
<<testForDEU1,cache=TRUE>>=
pasillaExons <- testForDEU( pasillaExons )
@ 
The function \Rfunction{DEUresultTable} provides a summary table of the results.
<<testForDEU2,cache=TRUE>>=
res <- DEUresultTable(pasillaExons)
<<testForDEU3>>=
table ( res$padjust < 0.1 )
@
%$
%------------------------------------------------------------
\section{Batch effects}\label{sec:glm}
%------------------------------------------------------------
In the last section we performed the analysis of differential exon usage ignoring the information regarding
the library type of the samples.  
<<design>>=
design(pasillaExons)
@
In this section, we show how to take the factor \Robject{type} into account in the analysis.
First, we need to provide the function \Rfunction{estimateDispersions} with a formula that makes
it aware of the additional factor (besides \Robject{condition}, which it considers by default).
%
<<formuladispersion,cache=TRUE>>=
formuladispersion <- count ~ sample + ( exon + type ) * condition
pasillaExons <- estimateDispersions( pasillaExons, formula = formuladispersion )
@
%
Second, for the testing, we will also change the two formulas to take into account the library type. 
%
<<formula1>>=
formula0 <- count ~ sample + type * exon + condition
formula1 <- count ~ sample + type * exon + condition * I(exon == exonID)
<<formula2,cache=TRUE>>=
pasillaExons <- testForDEU( pasillaExons, formula0=formula0, formula1=formula1 )
res <- DEUresultTable( pasillaExons )
<<formula3>>=
table( res$padjust < 0.1 )
@
%$


Are the results better? Compare.

%--------------------------------------------------
\section{Visualization}
%--------------------------------------------------
\Rpackage{DEXSeq} has a function to visualize the results of \Rfunction{testForDEU} with options for plotting the 
normalized counts for each of the exons, or the fitted expression estimates of the glm (Figure~\ref{figplot1}). 
%
<<plot1, fig=TRUE, height=8, width=12>>=
plotDEXSeq(pasillaExons, "FBgn0010909", cex.axis=1.2, cex=1.3, lwd=1.5)
@
\begin{figure}
\centering
\includegraphics[width=\textwidth]{DEXSeq-plot1}
\caption{The plot represents the expression estimates from a call to \texttt{testForDEU}.
Shown in red is the exon that showed significant differential exon usage.}
\label{figplot1}
\end{figure}

<<checkClaim,echo=FALSE>>=
wh = (fData(pasillaExons)$geneID=="FBgn0010909")
stopifnot(sum(fData(pasillaExons)$padjust[wh] < formals(plotDEXSeq)$FDR)==1)
@ 

Optionally, one can also visualize the transcript models (Figure~\ref{figplot2}), which might be
useful for putting differential exon usage results into the context of isoform regulation.
%
<<plot2, fig=TRUE, height=8, width=12>>=
plotDEXSeq(pasillaExons, "FBgn0010909", displayTranscripts=TRUE, cex.axis=1.2, cex=1.3, lwd=2, legend=TRUE)
@
\begin{figure}
\centering
\includegraphics[width=\textwidth]{DEXSeq-plot2}
\caption{As in Figure~\ref{figplot1}, but including the annotated transcript models.}
\label{figplot2}
\end{figure}

Another useful option is to look at the count values from the individual samples, rather than at the
model effect estimates. For this display, it is useful to normalize the counts by the size factors (Figure~\ref{figplot3}).
%
<<plot3, fig=TRUE, height=8, width=12>>=
plotDEXSeq(pasillaExons, "FBgn0010909", coefficients=FALSE, norCounts=TRUE, cex.axis=1.2, cex=1.3, lwd=2)
@
\begin{figure}
\centering
\includegraphics[width=\textwidth]{DEXSeq-plot3}
\caption{As in Figure~\ref{figplot1}, with normalized count values of each exon in each of the samples.}
\label{plot3}
\end{figure}

To generate an easily browsable, detailed overview over all analysis results, 
the package provides an HTML report generator, implemented in the function \Rpackage{DEXSeqHTML}.  
This function uses the package \Rpackage{hwriter} to create a result table with links to plots for the 
significant results, allowing a more detailed exploration of the results. To see an example of it, visit 
\url{http://www.embl.de/~reyes/DEXSeqReport/testForDEU.html}. The report shown there was generated using the code:
%
<<DEXSeqHTML,cache=TRUE>>=
DEXSeqHTML( pasillaExons, FDR=0.1, color=c("#FF000080", "#0000FF80") )
@

%--------------------------------------------------
\section{Gene count table}
%--------------------------------------------------
The user can also create gene count tables with the function \Rfunction{geneCountTable}, which basically sums
all the count exons with the same geneID.  This might be useful to give an input to other packages like 
\Rpackage{DESeq} or \Rpackage{edgeR}.
<<gct>>=
head(geneCountTable(pasillaExons))
@ 

%--------------------------------------------------
\section{Creating \Rclass{ExonCountSet} objects}\label{sec:creating}
%--------------------------------------------------
\subsection{From files produced by \texttt{HTSeq}}
and exploration of the results, but this requires information about the transcript annotation.  
To this extend, DEXSeq provides two python HTSeq scripts, dexseq\_prepare\_annotation.py and 
dexseq\_count.py.  The first script parses an annotation gtf file to define non-overlapping 
exonic regions: e.g. if a gene contains 2 exons that overlap, the script would define 2 exonic 
regions for the non-overlapping part of each exon and a third one for the overlapping part. 
It gives as output a second gtf file with the defined aggregated exonic regions.  The script 
dexseq\_count.py takes the gtf file provided by dexseq\_prepare\_annotation.py and an alignment 
in sam format and counts the number of reads falling in each of the defined exonic regions. 
\\
The DEXSeq function \Rfunction{read.HTSeqCounts} is able to read the output of these scripts 
and returns an ExonCountSet object with the proper information to make the analysis for 
differential exon usage as well as to generate the visualization of the results. If preferred, 
the user could also insert the annotation information manually to the ExonCountSet object 
directly after creating it. The example files can be seen with the function \Rfunction{system.file}.
For more details about the data set information see the vignette of the package \Rpackage{pasilla}.

For more
  information of the preprocessing of this dataset, please take a look
  to the vignette of the \Rpackage{pasilla}.

\subsection{From elementary R data structures}
The user can also provide its own data directly to the function \Rfunction{newExonCountSet} without 
using the HTSeq scripts.  To create an \Rclass{ExonCountSet} object, the minimum requirements are a exon count matrix
containing a row for every exon and a column for every sample, a vector or matrix with the design of the samples
and two vectors of gene and exon identificators of the same length as the number of rows of the count matrix.
With this object it is possible to make the analysis for differential exon usage, but the visualization functions
won't be so useful. Information about the exons (e.g. start and end positions) can be given as a data frame to 
the \Rfunction{newExonCountSet} function, or can be added to the \Rclass{ExonCountSet} object after its creation
via the \Rfunction{featureData}.
For more specifics,  see the man pages of \Rfunction{newExonCountSet}.
%
<<ecswithout,eval=FALSE>>=
ecs.without.annotation <- newExonCountSet(
   countData=counts(ecs), 
   design=design(ecs), 
   geneIDs=geneIDs(ecs), 
   exonIDs=exonIDs(ecs))

head(fData(ecs.without.annotation))
@
%$

\bibliography{DEXseq}
\bibliographystyle{plain}

\section{Session Information}
<<sessionInfo>>=
sessionInfo()
@ 
\end{document}
